### ISSUE TITLE
Non-clippy lints

### ISSUE THREAD

**Issue by emilk** [ericseppanen/cargo-cranky#4]
Thanks for `cargo cranky`!

There are lints outside of `clippy` that I often enable, for instance:

```
    "-Dunsafe_code",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    "-Wrustdoc::missing_crate_level_docs",
    "-Wsemicolon_in_expressions_from_macros",
    "-Wtrivial_casts",
    "-Wtrivial_numeric_casts",
    "-Wunused_extern_crates",
    "-Wunused_import_braces",
```

It would be wonderful if Cranky could handle these non-clippy lints as well, as then it would be a very good solution to https://github.com/rust-lang/cargo/issues/5034

---

Currently I enable clippy and non-clippy lints in `.cargo/config.toml` (https://github.com/emilk/egui/blob/e76c919c7e70c208c9a6209b9fe3369e7b6db99d/.cargo/config.toml) but it is a bit of a hack and has some problems (https://github.com/emilk/egui/issues/1439).

**Comment by ericseppanen** [comment]
I agree, this should be supported. I'm not sure why I didn't think of this use-case before; I guess I was just over-focused on clippy lints.

I suppose the right thing is to require clippy lints to be specified with their full name, i.e. `clippy::cast_lossless` rather than just `cast_lossless`. I was probably wrong to take this shortcut originally.

**Comment by ericseppanen** [comment]
This should work as of cargo-clippy 0.3.0. Please let me know if it works for your use case!

**Comment by emilk** [comment]
Works like a charm, thanks! ❤️
